### ISSUE TITLE
[subnet] Incorrect if condition in `get_validator_set`

### ISSUE THREAD

**Issue by dimitrovmaksim** [ava-labs/avalanche-rs#105]
While researching the rust implementation, we noticed there’s a check in [get_validator_set](https://github.com/ava-labs/avalanche-rs/blob/main/crates/avalanche-types/src/subnet/rpc/snow/validators/client.rs#L70) if [reps.validators](https://github.com/ava-labs/avalanche-rs/blob/main/crates/avalanche-types/src/subnet/rpc/snow/validators/client.rs#L91) is empty in order to get the `publick_key` variable updated. But if `resp.validators` is empty, wouldn’t it skip [the loop](https://github.com/ava-labs/avalanche-rs/blob/main/crates/avalanche-types/src/subnet/rpc/snow/validators/client.rs#L87) in the first place? We are assuming there it should check if `validator.public_key` is empty instead, because it seems it’s returned as a bytes array, and if the validator does not have a public key, the array would be empty. Are our assumptions correct or are we missing something?

**Comment by richardpringle** [comment]
Haha 😅 

Mind opening a PR? That's definitely some dead code that you've found. However, before you do, I just want either @hexfusion or @gyuho to chime in here and let us know if it's valid for validators in the `GetValidatorSetResponse` to have empty keys. *I think* it is, but I just want to be sure.

**Comment by dimitrovmaksim** [comment]
From the code docs i'm assuming it's possible https://github.com/ava-labs/awm-relayer/blob/2367600d8908fd49db57f4713e98cbeb9863b81b/relayer/canonical_validator_client.go#L92
