### ISSUE TITLE
[subnet] create cargo plugin to initialize new vm 

### ISSUE THREAD

**Issue by hexfusion** [ava-labs/avalanche-rs#44]
To improve UX for new Rust VM developers we could create cargo plugin that would initialize a new vm template, include examples etc.

```
cargo subnet new myvm
```

ref. https://www.youtube.com/watch?v=cUB4PXPKrnU

**Comment by richardpringle** [comment]
For templates, we could use https://crates.io/crates/cargo-generate

**Comment by dimitrovmaksim** [comment]
I'm looking into this

**Comment by richardpringle** [comment]
Thanks for the contribution (#93) @dimitrovmaksim!
